### ISSUE TITLE
results not as expected

### ISSUE THREAD

**Issue by zhyanlin** [lhqxinghun/TADfit#1]
Hello,
I tried to run TADfit on the combined GM12878 data at 10kb for chr6.  I set parameters as follows:

resolution <- 10000
start <- 0
end <- 170805979
start_time <- Sys.time()
TADs <- calltad(dirin, resolution, start, end)  #Other parameters are default

I expected to get TAD annotations similar to your manuscript. But these TAD annotations are like this figure:
![image](https://user-images.githubusercontent.com/9147453/178185398-4accc042-05e8-4d84-9883-52b31b86bc0f.png)

It missed a lot of TADs but only annotated three small TADs in this large region. To improve it, what should I do?

**Comment by lhqxinghun** [comment]
Thanks for your feedback. From the results, it seems that there is already a problem in the boundary detection step. However I cannot see a clue in the code you showed. It's more like an input data processing issue than a parameter setting issue. As a detailed example, I reprepared the contact matrices of chr6 on GM12878 cells (downloaed from https://bcm.app.box.com/v/aidenlab) at 10k resolution and ran TADfit on them. We got 734 TADs on Raw data and 691 TADs on CPMed data respectively. Here is our process and corresponding script (See the attachment). Hope it will help you.

(1) extract sparse matrices via juicer_tools (extract.txt)
(2) prepare input matrices via dump2matrix followed by CPM（CPM is optional but recommended since the IF distribution for different dataset varies, and the code for these two steps are in dump2matrix.R and CPM.R respectively）
(3) run the test script (TADfit_test_chr6.R)
The results are stored in TADs_Raw.txt and TADs_CPMed.txt respectively.

If the above steps are not appropriate for your situation, please make sure that your input data is not logarithmically processed (this step is already integrated within TADfit). You may also improve the performance by tryingTADfit on a shorter segment of a chromosome (e.g. 10Mb or 20 Mb) for high-resolution matrices
[process.zip](https://github.com/lhqxinghun/TADfit/files/9092543/process.zip)
.

**Comment by zhyanlin** [comment]
Thanks for your reply. It works now. My data is ice normalized with the sum of each row equal to 1. I realized it should be rescaled to the original read counts.
